apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vsTykvainVqapAAU1b0u/jCtn7W+QB+1VLSYw4qxlrbbZ7B9UGm5Eg==,iv:/riECu+AGvINfUEV8qw6t0TuVHrSQHglPBNQm/9nr/M=,tag:LsVWfyT3IRW+EssWZflpgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9tty2sjqqzkgc3dj44rcrvs99vpnfv7zjezgvgsjf6ncc4jpp9sm0pwvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHdBd0h1ZjVYaU1keTRi
            UEswbUZ6Sm1MZXVISFJrcDE1VmU5NzdyS0FNCllMZ0tRUkcxRUk0MS9FaHRiZis3
            aWFRUC9lSXYvNUhQcUNnN05tNi9oVXMKLS0tIDA4dXE1c2dvOWlEYTJoM3M4SFkz
            ZFpyU3k5NzRGRmFlZVZHNXR3MDhnQUkKzFylO3Z6Hvr/NwhoLDDgKLDGQ2a5RFww
            8m/vBfIci6AZbEqgKB5fliVxCfmtTv29aFsPHjisFmlY0bQuP9UUAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T14:26:58Z"
    mac: ENC[AES256_GCM,data:rD0iMzmyKzbOalyNKDrmnpg5edOpWoFH8NMOKlqG4WAWRRuX7KxUqfO8Xigu7Wl/d0a//B1BIv8v9ovc6hE7xh5voNNI4xB6QJD76kSO7AE5LHWsIZl2YW4WBV8JDgbPAPMEvR5CsRmJU0UHIk9SRjawN1bDwMqUEiEFaVG8Bbc=,iv:dJ+6joYlkm+mf3aCxUKdgUVsZOMTAjeVKILmgliBl7g=,tag:6HTwHwh7A7OhiLED2Ph+YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
