---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "10.96.8.35"
  METALLB_LB_RANGE: "10.96.8.40-10.96.8.50"
  METALLB_K8S_GATEWAY_ADDR: "10.96.8.40"
  METALLB_INGRESS_ADDR: "10.96.8.41"
