apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8e4cgBT7o9H3MzAw5A==,iv:ptwIKszoYGPbr4qgPIo9duNAN4t0xdb2RnkSEAs9c6M=,tag:zDqIlQvPXzJSkKbZo4aKGg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vUZ+ALhd5IgX8jnyjqFp2VTEPsMr,iv:UhnqvCz6iGmAy3SVXRJRsrlsfPv+NB4tBn3tWBKSU0Q=,tag:Aplz6Jzqo3a+iID2FT7MXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9tty2sjqqzkgc3dj44rcrvs99vpnfv7zjezgvgsjf6ncc4jpp9sm0pwvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWE9PQmxVdVpvSkhMNlhy
            TmNwNkdKUExLMkR5QmZBcDhuaW1iZDI0OVdjCkxETzVPanBOdnJnUnBBUUxjZkNk
            UWN0QmxRZHkxeTBqdy9UY2NaZGhZTU0KLS0tIGs3SndtKzBHN1JLMmdKYXZ0UkI0
            UWV2QklZWnBGMlhDTmw4ZkRnOWQ2T3MKmKvakvmGoB3Ck3EgiAsQweddMviK7jc5
            +BlHRE4vWjEMmjZWh68zhQmhD007pFOu989bre4HK89wX2PfkKkHmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T14:26:57Z"
    mac: ENC[AES256_GCM,data:K1bQt9Y3sNUw4FjiQXK2gtrnulTRkrNiIQYjgIvM5qUhqOVuMF7g8hQF5eCLKj7F2ewfFq2OqSbHT3vzSZ3ud3nV9Ud2GdBGbObOzoOacYo1Nu5kXmg76h3V2y9D3hKszs1pnaHPxd+8CiC1GOzfzrcEsjCGJOfvDjFKe+OFFd4=,iv:b2uxW+w3ipmz2hdXl2C8Y59eUhW1nFED/Qk3lI+m/2Y=,tag:H9NTmXWWzdR/UlT83HA6Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
